name: API Continuous Automation

"on":
  push:
    branches:
      - main

permissions:
    id-token: write
    contents: read

  # pull_request:
  # schedule:
  #  - cron: '0 0 * * *' # Run daily at midnight UTC
#  workflow_dispatch:
#    inputs:
#      run-tests:
#        description: 'Manually trigger the tests'
#        required: true
#        default: 'true'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12  # Specify the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: ${{ github.workspace }}

    - name: Run Pytest and generate test summary
      run: |
            pytest -v tests/test_booking_apis.py > test_summary.txt
      continue-on-error: true

    - name: Parse test results and generate email body
      run: |
            python parse_report.py
#    - name: Save test report as artifact
#      uses: actions/upload-artifact@v4
#      with:
#          name: html-report
#          path: reports/

    - name: Send email with HTML report
      uses: dawidd6/action-send-mail@v3
      with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "API Automation Report: Pytest Test Results"
          body: email_body.html
          to: niyazhashmi161921@gmail.com
          from: niyazhashmi161921@gmail.com
          attachments: reports/report.html
          secure: true